# KartaAuctionHouse Configuration

# --- Auction Settings ---
auction:
  max-auctions-per-player: 5
  auction-duration: 48h
  bid-increment: 5% # or flat value
  anti-sniping-extension: 30s
  tax-percentage: 5
  notification-methods: [chat, actionbar, title, sound]

# --- Economy Settings ---
economy:
  # Preferred economy provider. Options: KARTAEMERALDCURRENCY, VAULT
  # The plugin will try to use this provider first.
  preferred: VAULT
  # Fallback provider if the preferred one is not found.
  fallback: VAULT
  # Sink account for tax and listing fees.
  sink:
    # Where to deposit collected fees. Options: NONE, VAULT_ACCOUNT, KARTA_ACCOUNT
    mode: NONE
    # The name of the account to deposit into (e.g., a server bank name).
    target: "server_treasury"

# --- Mailbox Settings ---
mailbox:
  enabled: true
  # How long (in days) claimed items should be kept in the database before being purged.
  # Note: This is for future implementation and is not enforced in this version.
  retention-days: 30

# --- GUI Settings ---
gui:
  # Title of the main auction house GUI.
  title-main: "&6KartaAuctionHouse"
  # Must be a multiple of 9.
  size: 54
  # Number of slots available for auction items (size - 9 for controls).
  items-per-page: 45

# --- Database Settings ---
database:
  type: MYSQL # Other types like YAML might be supported later.
  host: "localhost"
  port: 3306
  database: "auctionhouse"
  username: "user"
  password: "password"
  pool-size: 10
  use-ssl: false
