name: KartaAuctionHouse
version: 2.0.0
main: com.minekartastudio.kartaauctionhouse.KartaAuctionHouse
author: MinekartaStudio
api-version: '1.21'
depend: [Vault]
softdepend: [PlaceholderAPI, KartaEmeraldCurrency]

commands:
  ah:
    description: Main command for KartaAuctionHouse.
    usage: /ah [subcommand]
    aliases: [auction, auctionhouse]
  kahdebug:
    description: Debug commands for KartaAuctionHouse troubleshooting.
    usage: /kahdebug [test|testitem|services|config|economy]
    permission: kartaauctionhouse.debug

permissions:
  kartaauctionhouse.use:
    description: Allows opening the main auction house GUI and using basic features.
    default: true
  kartaauctionhouse.sell:
    description: Allows listing items for sale using /ah sell.
    default: true
  kartaauctionhouse.cancel:
    description: Allows cancelling your own auctions (if they have no bids).
    default: true
  kartaauctionhouse.reload:
    description: Allows reloading the plugin's configuration files.
    default: op
  kartaauctionhouse.debug:
    description: Access to debug commands for troubleshooting.
    default: op
  kartaauctionhouse.admin:
    description: Access to all administrative features.
    default: op
    children:
      kartaauctionhouse.reload: true
      kartaauctionhouse.search: true
      kartaauctionhouse.categories: true
      kartaauctionhouse.notify: true
      kartaauctionhouse.history: true
      kartaauctionhouse.history.others: true
      kartaauctionhouse.debug: true

  kartaauctionhouse.search:
    description: Allows using /ah search.
    default: true
  kartaauctionhouse.categories:
    description: Allows using /ah categories.
    default: true
  kartaauctionhouse.notify:
    description: Allows toggling notifications.
    default: true
  kartaauctionhouse.history:
    description: Allows viewing personal auction history.
    default: true
  kartaauctionhouse.history.others:
    description: Allows viewing others' auction history.
    default: op
