name: PlayerAuctions
version: 2.0.0
main: com.minekarta.playerauction.PlayerAuction
author: MinekartaStudio
api-version: '1.21'
depend: [Vault]
softdepend: [PlaceholderAPI, KartaEmeraldCurrency]

commands:
  ah:
    description: Main command for PlayerAuctions - open auction house or manage listings.
    usage: /ah [subcommand] [arguments]
    aliases: [auction, auctionhouse]
  auction:
    description: Alternative main command for PlayerAuctions - open auction house or manage listings.
    usage: /auction [subcommand] [arguments]
    aliases: [ah, auctionhouse]
  auctionhouse:
    description: Alternative main command for PlayerAuctions - open auction house or manage listings.
    usage: /auctionhouse [subcommand] [arguments]
    aliases: [ah, auction]

permissions:
  playerauctions.use:
    description: Allows opening the main auction house GUI and using basic features.
    default: true
  playerauctions.sell:
    description: Allows listing items for sale using /ah sell.
    default: true
  playerauctions.cancel:
    description: Allows cancelling your own auctions (if they have no bids).
    default: true
  playerauctions.reload:
    description: Allows reloading the plugin's configuration files.
    default: op
  playerauctions.admin:
    description: Access to all administrative features.
    default: op
    children:
      playerauctions.reload: true
      playerauctions.search: true
      playerauctions.categories: true
      playerauctions.notify: true
      playerauctions.history: true
      playerauctions.history.others: true

  playerauctions.search:
    description: Allows using /ah search.
    default: true
  playerauctions.categories:
    description: Allows using /ah categories.
    default: true
  playerauctions.notify:
    description: Allows toggling notifications.
    default: true
  playerauctions.history:
    description: Allows viewing personal auction history.
    default: true
  playerauctions.history.others:
    description: Allows viewing others' auction history.
    default: op
