name: KartaAuctionHouse
version: 2.0.0
main: com.minekartastudio.kartaauctionhouse.KartaAuctionHouse
author: MinekartaStudio
api-version: '1.21'
depend: [Vault]
softdepend: [PlaceholderAPI, KartaEmeraldCurrency]

commands:
  ah:
    description: Main command for KartaAuctionHouse.
    usage: /ah [subcommand]
    aliases: [auction, auctionhouse]

permissions:
  kartaauctionhouse.use:
    description: Allows opening the main auction house GUI and using basic features.
    default: true
  kartaauctionhouse.sell:
    description: Allows listing items for sale using /ah sell.
    default: true
  kartaauctionhouse.cancel:
    description: Allows cancelling your own auctions (if they have no bids).
    default: true
  kartaauctionhouse.reload:
    description: Allows reloading the plugin's configuration files.
    default: op
  kartaauctionhouse.admin:
    description: Access to all administrative features.
    default: op
    children:
      kartaauctionhouse.reload: true
